server:
  port: 14000

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
      -  id: consumerService
         uri: http://localhost:12000
         predicates:
           -  Path=/cart/getUserById/**

