server:
  port: 12000

spring:
  application:
    name: consumer-server

eureka:
  client:
    service-url:
      #需要注册给Eureka Server的地址，也就是将自己注册给哪一个Eureka Server
      defaultZone: http://eurekaServer13000:13000/eureka,http://eurekaServer13001:13001/eureka

#需要调用的微服务名称
provider-server:
  ribbon:
  #设置使用哪一种负载均衡策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#断路器
resilience4j:
  circuitbreaker:
    configs:
      CircuitBreakerAConfig:
        failure-rate-threshold: 30
        sliding-window-size: 10
        sliding-window-type: time_based
        minimum-number-of-calls: 5
        wait-duration-in-open-state:
          seconds: 5
        permitted-number-of-calls-in-half-open-state: 3

      CircuitBreakerBConfig:
        sliding-window-size: 5
        minimum-number-of-calls: 3
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state:
          seconds: 5
        failure-rate-threshold: 50
        slow-call-duration-threshold:
          seconds: 2
        slow-call-rate-threshold: 30

    instances:
      CircuitBreakerA:
        base-config: CircuitBreakerAConfig

      CircuitBreakerB:
        base-config: CircuitBreakerBConfig
  #隔离器
  bulkhead:
    configs:
      bulkheadAConfig:
        max-concurrent-calls: 10
        max-wait-duration:
          seconds: 20

    instances:
      bulkheadA:
        base-config: bulkheadAConfig
  #限流器
  ratelimiter:
    configs:
      ratelimitAConfig:
        limit-for-period: 5
        timeout-duration:
          seconds: 1
        limit-refresh-period:
          seconds: 2
    instances:
      ratelimiterA:
        base-config: ratelimitAConfig


